
### ADD ORDERS
POST http://localhost:8888/orderid/
Content-Type: application/json

{
  "numberorder": "99999367888"
}

###
DELETE http://localhost:8888/orderid/8/
Content-Type: application/json

###
PUT http://localhost:8888/orderid/10/
Content-Type: application/json

{
  "numberorder": "33311111111"
}


### ADD CLIENT
POST http://localhost:8888/clients/
Content-Type: application/json

{
  "username": "mixamus",
  "firstname": "Max",
  "lastname": "Dokuchaev",
  "password": "qwerty13",
  "phone": "89299205153"
}

###
PUT http://localhost:8888/clients/8/
Content-Type: application/json

{
  "username": "dimono",
  "firstname": "Dered",
  "lastname": "Ser",
  "password": "12345678",
  "phone": "81234567878"
}

###
DELETE http://localhost:8888/clients/8/
Content-Type: application/json


### ADD PART
POST http://localhost:8888/parts/
Content-Type: application/json

{
  "namepart": "Dno",
  "vin": "YV1960ASX44444444",
  "model": "BMV",
  "year": 2013,
  "availability": "IN_STOCK"
}

###
PUT http://localhost:8888/parts/v2/8/
Content-Type: application/json

{
  "namepart": "Stupista",
  "vin": "WEQ42564787954",
  "model": "Opel",
  "year": 2009,
  "availability": "NON_STOCK"
}

###
DELETE http://localhost:8888/parts/7/
Content-Type: application/json