###
POST http://localhost:8888/orderid/
Content-Type: application/json

{
  "numberorder": "99999367888"
}

###
POST http://localhost:8888/clients/
Content-Type: application/json

{
  "username": "mixamus",
  "firstname": "Max",
  "lastname": "Dokuchaev",
  "password": "qwerty13",
  "phone": "89299205153"
}