server:
  port: 8888

spring:
  security:
    user:
      name: mixamus
      password: qwerty13

  jpa:
    open-in-view: false

  datasource:
    url: jdbc:postgresql://localhost:5454/postgres
    username: postgres
    password: postgres
