server:
  port: 8888

spring:
  datasource:
    url: jdbc:postgresql://localhost:5454/postgres
    username: postgres
    password: postgres

  security:
    user:
      name: mixamus
      password: qwerty13

  jpa:
    open-in-view: false
    show-sql: true # false стоит по умолчанию, с true будет в консоли гененировать sql запросы